
package net.awired.housecream.server.core.engine

rule "light on"  
    when
        PointStat(PointId == 1, value == 1)
        PointStat(PointId == 2, value == 0)
    then
        System.out.println("turn on the light 42");
end

rule "light off"
    when
        PointStat(PointId == 1, value == 1)
        PointStat(PointId == 2, value == 1)
    then
        System.out.println("turn off the light 42");
end


rule "alarm on"
    salience 10
    when
        AlarmMode(this == AlarmMode.NORMAL)
        PointStat(PointId == 1, value == 1)
    then
        System.out.println("Alarm!!!!!!!!!");
end
